kind: Service
apiVersion: v1
metadata:
  name: hello
  labels:
    shipper-lb: production
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80