apiVersion: shipper.booking.com/v1alpha1
kind: Application
metadata:
  name: lionelrichieapp
spec:
  revisionHistoryLimit: 3
  template:
    chart:
      name: hello
      repoUrl: https://raw.githubusercontent.com/tettaji/shipper-test/master/
      version: 1.0
    clusterRequirements:
      regions:
      - name: local
    strategy:
      steps:
      - name: staging
        capacity:
          incumbent: 100
          contender: 33
        traffic:
          incumbent: 100
          contender: 0
      - name: canary
        capacity:
          incumbent: 50
          contender: 50
        traffic:
          incumbent: 50
          contender: 50
      - name: full on
        capacity:
          incumbent: 0
          contender: 100
        traffic:
          incumbent: 0
          contender: 100
    values:
      replicaCount: 3